<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { Activity, CheckCheck, Clock3, Coins, TriangleAlert, RefreshCw, ArrowUpRight } from 'lucide-vue-next';
import PageHeading from '../components/PageHeading.vue';
import MetricChart from '../components/MetricChart.vue';
import RequestFeedback from '../components/RequestFeedback.vue';
import { useRequest } from '../composables/useRequest';
import { getMetrics } from '../services/metrics';
import { dailySeries, distribution, trend } from '../utils/charts';
import { formatNumber } from '../utils/context';
import type { Metrics } from '../types';
const request = useRequest(); const metrics = ref<Metrics>(); const samples = ref(true); const now = new Date(); const start = new Date(); start.setDate(start.getDate() - 13); const range = ref<[string, string]>([start.toISOString().slice(0, 10), now.toISOString().slice(0, 10)]);
const days = computed(() => dailySeries(metrics.value?.records || [], range.value[0], range.value[1]));
const stats = computed(() => [{ name: 'Total requests', value: formatNumber(metrics.value?.totalRequests || 0), icon: Activity, note: 'Across chat, tools and retrieval' }, { name: 'Success rate', value: (metrics.value?.successRate || 0).toFixed(1) + '%', icon: CheckCheck, note: 'Successful / all recorded requests' }, { name: 'Average latency', value: ((metrics.value?.avgLatency || 0) / 1000).toFixed(2) + 's', icon: Clock3, note: 'End-to-end request duration' }, { name: 'Total tokens', value: formatNumber(metrics.value?.totalTokens || 0), icon: Coins, note: 'Reported or estimated usage' }, { name: 'Error count', value: metrics.value?.errorCount || 0, icon: TriangleAlert, note: 'Excludes user-aborted requests' }]);
const charts = computed(() => { const records = metrics.value?.records || []; const labels = days.value.map(d => d.date); return [{ title: 'Daily requests', subtitle: 'Request volume over time', option: trend(labels, days.value.map(d => d.requests), 'bar'), large: true }, { title: 'Token usage', subtitle: 'Input and output tokens combined', option: trend(labels, days.value.map(d => d.tokens)), large: true }, { title: 'Latency trend', subtitle: 'Daily average · milliseconds', option: trend(labels, days.value.map(d => d.latency), 'line', '#b49c72'), large: true }, { title: 'Model distribution', subtitle: 'Requests by configured model', option: distribution(records, 'model') }, { title: 'Request outcomes', subtitle: 'Success, error and cancellation', option: distribution(records, 'status') }, { title: 'Tool usage', subtitle: 'Executions by tool name', option: distribution(records.filter(r => r.kind === 'tool'), 'tool') }, { title: 'Knowledge retrieval', subtitle: 'Search requests per day', option: trend(labels, days.value.map(d => d.retrieval), 'bar', '#a7bb82'), large: true }]; });
async function load() { if (!range.value?.[0] || !range.value?.[1]) return; const data = await request.run((signal) => getMetrics(range.value[0], range.value[1], samples.value, signal)); if (data) metrics.value = data; } onMounted(load);
</script>
<template><div class="page"><PageHeading title="Monitoring" description="A clear view of how your AI workspace is performing."><el-date-picker v-model="range" type="daterange" value-format="YYYY-MM-DD" format="MMM D" range-separator="—" start-placeholder="Start date" end-placeholder="End date" :clearable="false" :disabled="request.loading.value" @change="load" /><el-button :icon="RefreshCw" :loading="request.loading.value" @click="load">Refresh</el-button></PageHeading><div class="monitoring-context"><div><span class="status-dot"></span>{{ metrics?.source || 'Loading request metrics' }}</div><el-checkbox v-model="samples" :disabled="request.loading.value" @change="load">Include synthetic demo baseline</el-checkbox></div><RequestFeedback :state="request.state.value" :error="request.error.value" @retry="load" @abort="request.abort" /><div class="stat-grid monitoring-stats"><div v-for="stat in stats" :key="stat.name" class="stat-card"><div class="stat-label">{{ stat.name }}<component :is="stat.icon" :size="16" /></div><div class="stat-value">{{ stat.value }}</div><div class="stat-note">{{ stat.note }}</div></div></div><div v-if="metrics && !metrics.records.length" class="panel empty-state"><Activity :size="32" /><h3>No activity in this date range</h3><p>Send a message, execute a tool, or enable the synthetic baseline.</p></div><div v-else class="charts-grid"><section v-for="chart in charts" :key="chart.title" class="panel chart-panel" :class="{ wide: chart.large }"><div class="panel-title"><div><h2>{{ chart.title }}</h2><p>{{ chart.subtitle }}</p></div><ArrowUpRight :size="15" class="muted" /></div><MetricChart :option="chart.option" :label="chart.title" /></section></div><div class="notice">Demo records are synthetic. Observed metrics come from this local BFF; token estimates are not billing statements. No provider pricing is assumed.</div></div></template>
<style scoped>.monitoring-context{display:flex;align-items:center;justify-content:space-between;margin:-4px 0 18px;color:#9aa68d;font-size:10px}.monitoring-context>div{display:flex;align-items:center;gap:7px}.monitoring-stats{grid-template-columns:repeat(5,1fr)}.monitoring-stats .stat-card{padding:19px 17px}.monitoring-stats .stat-note{font-size:8px}.charts-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:20px}.chart-panel{grid-column:span 2;padding:20px 20px 9px}.chart-panel.wide{grid-column:span 3}.chart-panel:last-child{grid-column:span 6}.chart-panel .panel-title{margin-bottom:9px}.chart-panel h2{font-size:13px}.chart-panel .panel-title p{font-size:9px}.page-heading :deep(.el-date-editor){width:225px;flex-grow:0;height:33px}.heading-actions :deep(.el-date-editor .el-range-input){font-size:11px}@media(max-width:1200px){.monitoring-stats{grid-template-columns:repeat(3,1fr)}.chart-panel{grid-column:span 3}}@media(max-width:800px){.monitoring-stats{grid-template-columns:repeat(2,1fr)}.chart-panel,.chart-panel.wide{grid-column:span 6}.monitoring-context{flex-direction:column;align-items:flex-start}.page-heading :deep(.el-date-editor){width:190px}}</style>
