import type { ChatRequest, StreamEvent } from '../../shared/types.js';
import { type AIProvider, estimateTokens } from './AIProvider.js';
import { AppError, delay } from '../utils/errors.js';
export class MockAIProvider implements AIProvider {
  async *stream(request: ChatRequest, signal: AbortSignal): AsyncGenerator<StreamEvent> {
    const start = Date.now();
    if (request.simulate === 'error') {
      await delay(350, signal);
      throw new AppError(503, 'MOCK_ERROR', 'Simulated provider failure. Use Retry to recover.');
    }
    if (request.simulate === 'timeout') await delay(request.timeoutMs + 500, signal);
    const question = request.messages.filter((m) => m.role === 'user').at(-1)?.content || '';
    const context = request.messages.find(
      (m) => m.role === 'system' && m.content.includes('[Source'),
    )?.content;
    let content = context
      ? `## Answer grounded in retrieved context\n\nYour question: **${question.slice(0, 180)}**\n\nThe selected documents describe a workflow that connects document preparation, retrieval and source-aware generation. Inspect the excerpts below before relying on this demonstration.\n\n${context
          .split('[Source')
          .slice(1, 4)
          .map(
            (s, i) => `**[Source ${i + 1}]**\n> ${s.split('\n').slice(1).join(' ').slice(0, 230)}`,
          )
          .join(
            '\n\n',
          )}\n\n*Mock synthesis: this response is deterministic, not an assessment by a real language model.*`
      : `## A practical starting point\n\nYou asked: **${question.slice(0, 220)}**\n\nHere is a structured approach for your next experiment:\n\n1. **Define the outcome.** Make the expected behavior observable and easy to verify.\n2. **Connect the right context.** Keep conversation history and source documents within the request budget.\n3. **Inspect each step.** Track tool results, token usage and response time independently.\n\n| Layer | Responsibility |\n| --- | --- |\n| Frontend | Streaming, state and user controls |\n| BFF | Provider credentials, limits and errors |\n| Provider | Model inference through a compatible API |\n\n\`\`\`typescript\nconst controller = new AbortController();\nawait streamChat(request, controller.signal);\n// Stop generation without losing the partial response\ncontroller.abort();\n\`\`\`\n\n> This response was generated by the Mock provider. ${request.messages.filter((m) => m.role === 'user').length} user turn(s) were included in the context. Configure a server-side provider to receive real model answers.`;
    content = content.slice(0, request.maxTokens * 3);
    for (let index = 0; index < content.length; index += 32) {
      await delay(50 + (index % 101), signal);
      yield { type: 'delta', content: content.slice(index, index + 32) };
    }
    const promptTokens = estimateTokens(request.messages.map((m) => m.content).join('\n'));
    const completionTokens = estimateTokens(content);
    yield {
      type: 'done',
      data: {
        content,
        model: request.model,
        latencyMs: Date.now() - start,
        usage: {
          promptTokens,
          completionTokens,
          totalTokens: promptTokens + completionTokens,
          estimated: true,
        },
      },
    };
  }
}
