import { createApp } from 'vue';
import { createPinia } from 'pinia';
import { ElMessage } from 'element-plus/es/components/message/index';
import 'element-plus/es/components/message/style/css';
import 'element-plus/es/components/message-box/style/css';
import '@fontsource/dm-sans/latin-400.css';
import '@fontsource/dm-sans/latin-500.css';
import '@fontsource/dm-sans/latin-600.css';
import '@fontsource/dm-sans/latin-700.css';
import '@fontsource/manrope/latin-500.css';
import '@fontsource/manrope/latin-600.css';
import '@fontsource/manrope/latin-700.css';
import '@fontsource/manrope/latin-800.css';
import 'element-plus/theme-chalk/dark/css-vars.css';
import 'highlight.js/styles/github-dark.css';
import './assets/main.css';
import './assets/workspaces.css';
import App from './App.vue';
import router from './router';
const app = createApp(App);
app.use(createPinia()).use(router);
app.config.errorHandler = (error) => {
  console.error('Component error:', error);
  ElMessage.error('This view encountered an error. Reload the page to recover.');
};
app.mount('#app');
